export const DEFAULT_STAGE_CONFIGS = [
  {
    stage: 'New',
    stageLabel: 'Stage 01: Lead Ingestion',
    templateName: 'Welcome & Expat Questionnaire',
    subject: 'Welcome to {{brokerage_name}} – Your German Mortgage Application',
    body: `Dear {{client_name}},\n\nThank you for reaching out to {{brokerage_name}}. We have received your inquiry for a German mortgage (Finanzierung) of {{loan_amount}} in {{city}}.\n\nYour assigned Mortgage Advisor {{advisor_name}} will review your information and get in touch within 24 hours.\n\nYou can access your personal Client Portal anytime at: {{portal_link}} to begin organizing your documents.\n\nBest regards,\n{{brokerage_name}} Advisory Team`,
    taskTitle: 'Initial qualification call with {{client_name}}',
    taskPriority: 'high',
    taskDueHours: 2,
  },
  {
    stage: 'Contacted',
    stageLabel: 'Stage 02: Initial Consultation',
    templateName: 'Consultation Summary & Budget',
    subject: 'Your Mortgage Consultation Summary with {{advisor_name}}',
    body: `Dear {{client_name}},\n\nIt was a pleasure speaking with you regarding your property purchase plans. As discussed, German mortgage lenders evaluate your Blue Card / Residence status, net household income, and equity capital (Eigenkapital).\n\nNext step: Please complete your financial profile on our secure portal at {{portal_link}}.\n\nBest regards,\n{{advisor_name}} | {{brokerage_name}}`,
    taskTitle: 'Follow-up on consultation notes & borrower budget',
    taskPriority: 'medium',
    taskDueHours: 24,
  },
  {
    stage: 'Document Collection',
    stageLabel: 'Stage 03: Document Collection',
    templateName: 'German Mortgage Document Checklist',
    subject: 'Action Required: Required German Mortgage Documents for {{client_name}}',
    body: `Dear {{client_name}},\n\nTo prepare your official bank submission (Bankanfrage), German lenders require standard compliance documentation:\n\n1. Last 3 Salary Slips (Gehaltsabrechnungen)\n2. Last Year-End Tax Summary (Lohnsteuerbescheinigung)\n3. SCHUFA Credit Report\n4. Copy of Passport & Residence Permit (Aufenthaltstitel)\n5. Real Estate Expose & Ground Plan (Grundriss)\n\nPlease upload these directly to your secure checklist at: {{portal_link}}.\n\nWarm regards,\n{{brokerage_name}} Document Verification Desk`,
    taskTitle: 'Audit client uploaded documents against German lender checklist',
    taskPriority: 'high',
    taskDueHours: 12,
  },
  {
    stage: 'Bank Submission',
    stageLabel: 'Stage 04: Bank Submission',
    templateName: 'Application Dispatched to Lenders',
    subject: 'Good News: Your Mortgage Application is Submitted to Lenders',
    body: `Dear {{client_name}},\n\nWe are pleased to inform you that your mortgage dossier has been officially dispatched to our German partner banking network (ING, Commerzbank, DSL Bank, Sparkasse).\n\nExpected lender review turnaround is 3-5 business days. We will notify you immediately once official loan terms and interest rate locks (Zinsbindung) are received.\n\nBest regards,\n{{advisor_name}} | {{brokerage_name}}`,
    taskTitle: 'Monitor banking portal for lender underwriter queries & rate locks',
    taskPriority: 'medium',
    taskDueHours: 48,
  },
  {
    stage: 'Won',
    stageLabel: 'Stage 05: Loan Approval & Offer',
    templateName: 'Mortgage Loan Offer Approved',
    subject: 'Congratulations! Your Mortgage Loan has been Approved',
    body: `Dear {{client_name}},\n\nCongratulations! We have secured final loan approval (Darlehenszusage) from the lender for {{loan_amount}}.\n\nPlease review your loan agreement and financing schedule in your portal at {{portal_link}} before signing.\n\nNext Step: We will coordinate with your Notary (Notariat) for the deed signing.\n\nBest regards,\n{{brokerage_name}}`,
    taskTitle: 'Prepare binding loan agreement (Darlehensvertrag) & dispatch to client',
    taskPriority: 'high',
    taskDueHours: 24,
  },
  {
    stage: 'Lost',
    stageLabel: 'Stage 06: Notary Appointment & Closing',
    templateName: 'Notary Preparation & Signing Guide',
    subject: 'Notary Appointment Preparation Guide & Closing Checklist',
    body: `Dear {{client_name}},\n\nYour notary appointment (Notartermin) is the final legal step to acquire your property in Germany.\n\nKey checklist items:\n- Valid original Passport & Registration Certificate (Meldebescheinigung)\n- German Tax ID (Steuer-ID)\n- Land charge deed authorization (Grundschuldbestellungsurkunde)\n\nCongratulations on reaching the finish line!\n\nBest regards,\n{{brokerage_name}}`,
    taskTitle: 'Verify Grundschuld land charge registration with notary office',
    taskPriority: 'medium',
    taskDueHours: 72,
  },
];
