export const DEFAULT_STAGE_CONFIGS = [
  {
    stage: 'New',
    stageLabel: 'Stage 01: Lead Ingestion',
    templateName: 'Welcome & Expat Questionnaire',
    subject: 'Welcome to {{brokerage_name}} – Your German Mortgage Application',
    body: `Dear {{client_name}},\n\nThank you for reaching out to {{brokerage_name}}. We have received your inquiry for a German mortgage (Finanzierung) of {{loan_amount}} in {{city}}.\n\nYour assigned Mortgage Advisor {{advisor_name}} will review your information and get in touch within 24 hours.\n\nYou can access your personal Client Portal anytime at: {{portal_link}} to begin organizing your documents.\n\nBest regards,\n{{brokerage_name}} Advisory Team`,
    taskTitle: 'Initial qualification call with {{client_name}}',
    taskPriority: 'high',
    taskDueHours: 2,
  },
  {
    stage: 'Contacted',
    stageLabel: 'Stage 02: Initial Consultation',
    templateName: 'Consultation Summary & Budget',
    subject: 'Your Mortgage Consultation Summary with {{advisor_name}}',
    body: `Dear {{client_name}},\n\nIt was a pleasure speaking with you regarding your property purchase plans. As discussed, German mortgage lenders evaluate your Blue Card / Residence status, net household income, and equity capital (Eigenkapital).\n\nNext step: Please complete your financial profile on our secure portal at {{portal_link}}.\n\nBest regards,\n{{advisor_name}} | {{brokerage_name}}`,
    taskTitle: 'Follow-up on consultation notes & borrower budget',
    taskPriority: 'medium',
    taskDueHours: 24,
  },
  {
    stage: 'Document Collection',
    stageLabel: 'Stage 03: Document Collection',
    templateName: 'German Mortgage Document Checklist',
    subject: 'Action Required: Required German Mortgage Documents for {{client_name}}',
    body: `Dear {{client_name}},\n\nTo prepare your official bank submission (Bankanfrage), German lenders require standard compliance documentation:\n\n1. Last 3 Salary Slips (Gehaltsabrechnungen)\n2. Last Year-End Tax Summary (Lohnsteuerbescheinigung)\n3. SCHUFA Credit Report\n4. Copy of Passport & Residence Permit (Aufenthaltstitel)\n5. Real Estate Expose & Ground Plan (Grundriss)\n\nPlease upload these directly to your secure checklist at: {{portal_link}}.\n\nWarm regards,\n{{brokerage_name}} Document Verification Desk`,
    taskTitle: 'Audit client uploaded documents against German lender checklist',
    taskPriority: 'high',
    taskDueHours: 12,
  },
  {
    stage: 'Bank Submission',
    stageLabel: 'Stage 04: Bank Submission',
    templateName: 'Application Dispatched to Lenders',
    subject: 'Good News: Your Mortgage Application is Submitted to Lenders',
    body: `Dear {{client_name}},\n\nWe are pleased to inform you that your mortgage dossier has been officially dispatched to our German partner banking network (ING, Commerzbank, DSL Bank, Sparkasse).\n\nExpected lender review turnaround is 3-5 business days. We will notify you immediately once official loan terms and interest rate locks (Zinsbindung) are received.\n\nBest regards,\n{{advisor_name}} | {{brokerage_name}}`,
    taskTitle: 'Monitor banking portal for lender underwriter queries & rate locks',
    taskPriority: 'medium',
    taskDueHours: 48,
  },
  {
    stage: 'Won',
    stageLabel: 'Stage 05: Loan Approval & Offer',
    templateName: 'Mortgage Loan Offer Approved',
    subject: 'Congratulations! Your Mortgage Loan has been Approved',
    body: `Dear {{client_name}},\n\nCongratulations! We have secured final loan approval (Darlehenszusage) from the lender for {{loan_amount}}.\n\nPlease review your loan agreement and financing schedule in your portal at {{portal_link}} before signing.\n\nNext Step: We will coordinate with your Notary (Notariat) for the deed signing.\n\nBest regards,\n{{brokerage_name}}`,
    taskTitle: 'Prepare binding loan agreement (Darlehensvertrag) & dispatch to client',
    taskPriority: 'high',
    taskDueHours: 24,
  },
  {
    stage: 'Lost',
    stageLabel: 'Stage 06: Notary Appointment & Closing',
    templateName: 'Notary Preparation & Signing Guide',
    subject: 'Notary Appointment Preparation Guide & Closing Checklist',
    body: `Dear {{client_name}},\n\nYour notary appointment (Notartermin) is the final legal step to acquire your property in Germany.\n\nKey checklist items:\n- Valid original Passport & Registration Certificate (Meldebescheinigung)\n- German Tax ID (Steuer-ID)\n- Land charge deed authorization (Grundschuldbestellungsurkunde)\n\nCongratulations on reaching the finish line!\n\nBest regards,\n{{brokerage_name}}`,
    taskTitle: 'Verify Grundschuld land charge registration with notary office',
    taskPriority: 'medium',
    taskDueHours: 72,
  },
];

export const DEFAULT_ACCOUNT_TEMPLATES = [
  {
    name: 'Client Account Deactivated & Suspended',
    subject: 'Important: Your {{brokerage_name}} Mortgage Portal Account has been Deactivated',
    body: `Dear {{client_name}},\n\nYour client portal account at {{brokerage_name}} has been temporarily deactivated or suspended by our brokerage administration team.\n\nReason / Details: {{reason}}\n\nWhile your account is suspended, your access to upload documents or submit financing applications is temporarily restricted.\n\nIf you believe this is an error or would like to resume your mortgage application process, please contact your assigned advisor {{advisor_name}} or email our support desk at {{support_email}}.\n\nBest regards,\n{{brokerage_name}} Administration Team`,
    description: 'Automated notification dispatched when a client account is suspended/deactivated by an admin',
  },
  {
    name: 'Client Account Reactivated & Restored',
    subject: 'Good News: Your {{brokerage_name}} Mortgage Portal Account is Active',
    body: `Dear {{client_name}},\n\nWe are pleased to inform you that your client portal account at {{brokerage_name}} has been reactivated.\n\nYou can now log in securely using your credentials:\n\nLogin Portal: {{portal_link}}\nLogin Email: {{client_email}}\nTemporary Password: {{temporary_password}}\n\nAccess your mortgage journey roadmap, view loan status updates, and upload compliance documents for advisor {{advisor_name}}.\n\nWelcome back!\n\nWarm regards,\n{{brokerage_name}} Advisory Team`,
    description: 'Automated notification dispatched when a client account is reactivated by an admin',
  },
  {
    name: 'Client Portal Welcome & Onboarding',
    subject: 'Access Your Secure Expat Mortgage Portal – {{brokerage_name}}',
    body: `Dear {{client_name}},\n\nWelcome to {{brokerage_name}}! Your dedicated German mortgage portal is now active.\n\nYou can log in securely to manage your mortgage application roadmap and upload compliance documents:\n\nLogin Portal: {{portal_link}}\nLogin Email: {{client_email}}\nTemporary Password: {{temporary_password}}\n\nAssigned Mortgage Advisor: {{advisor_name}} ({{advisor_email}})\n\nBest regards,\n{{brokerage_name}} Team`,
    description: 'Welcome and initial portal credentials for registered borrowers',
  },
  {
    name: 'Document Verification Failed & Revision Request',
    subject: 'Action Required: Document Revision for Your Mortgage Application – {{brokerage_name}}',
    body: `Dear {{client_name}},\n\nYour mortgage advisor {{advisor_name}} or partner bank underwriter has reviewed your submitted documents and requested corrections / re-upload for your mortgage application.\n\nReason: {{reason}}\n\nPlease log in to your Document Vault at {{vault_link}} and submit updated compliant versions so we can finalize your bank submission.\n\nBest regards,\n{{advisor_name}} | {{brokerage_name}}`,
    description: 'Dispatched when documents fail compliance/underwriting verification and require re-upload',
  },
  {
    name: 'Mortgage Advisor Assigned Notice',
    subject: 'Meet Your Dedicated Mortgage Advisor at {{brokerage_name}}',
    body: `Dear {{client_name}},\n\nWe are pleased to inform you that {{advisor_name}} has been assigned as your dedicated Mortgage Advisor for your property financing in {{city}}.\n\nAdvisor Contact Information:\nEmail: {{advisor_email}}\nPhone: {{advisor_phone}}\n\nCurrent Application Stage: {{stage_label}}\n\nYou can track your application progress and message your advisor through your portal at {{portal_link}}.\n\nBest regards,\n{{brokerage_name}} Advisory Desk`,
    description: 'Dispatched to the borrower when a mortgage advisor is assigned or reassigned to their lead file',
  },
  {
    name: 'Password Reset Verification Code',
    subject: 'Your Password Reset Verification Code: {{reset_code}} – {{brokerage_name}}',
    body: `Dear {{user_name}},\n\nWe received a request to reset the password for your {{brokerage_name}} account ({{user_email}}).\n\nYour 6-digit verification code is:\n\n{{reset_code}}\n\nThis verification code is valid for 15 minutes. If you did not request this password reset, you can safely ignore this email and your password will remain unchanged.\n\nDirect Reset Link: {{reset_url}}\n\nBest regards,\n{{brokerage_name}} Security Desk`,
    description: 'Automated verification code sent when a user requests a password reset',
  },
  {
    name: 'Password Reset Confirmation Notice',
    subject: 'Security Alert: Your Password Was Successfully Updated – {{brokerage_name}}',
    body: `Dear {{user_name}},\n\nThis is a confirmation that the password for your {{brokerage_name}} account ({{user_email}}) was successfully updated.\n\nIf you did not make this change, please contact our security team immediately.\n\nSign In: {{login_url}}\n\nBest regards,\n{{brokerage_name}} Security Desk`,
    description: 'Security confirmation dispatched after a user successfully resets their password',
  },
];

