export const DEMO_LEADS_CONFIG = [
  {
    firstName: 'Rahul',
    lastName: 'Sharma',
    email: 'rahul.sharma@techberlin.de',
    phone: '+49 170 1234567',
    loanAmount: 480000,
    purchasePrice: 600000,
    city: 'Berlin',
    visaType: 'EU Blue Card',
    employmentType: 'Employed (Permanent)',
    monthlyNetIncome: 5600,
    stage: 'New',
    advisorEmail: 'mortgageadvisor@gmail.com',
    sourceName: 'Immobilienscout24 Expat Leads',
    notes: 'Senior Software Architect in Kreuzberg. Looking for 80% LTV financing with 10-year rate lock.',
  },
  {
    firstName: 'Maria',
    lastName: 'Gonzalez',
    email: 'maria.gonzalez@biopharm.com',
    phone: '+49 176 9876543',
    loanAmount: 650000,
    purchasePrice: 820000,
    city: 'Munich',
    visaType: 'Permanent Residence (Niederlassungserlaubnis)',
    employmentType: 'Employed',
    monthlyNetIncome: 6800,
    stage: 'Contacted',
    advisorEmail: 'brokerageadmin@gmail.com',
    sourceName: 'Typeform Expat Mortgage Funnel',
    notes: 'Clinical Trial Director in Schwabing. Has €170k Eigenkapital equity saved.',
  },
  {
    firstName: 'David',
    lastName: 'Kowalski',
    email: 'david.kowalski@fintech-frankfurt.eu',
    phone: '+49 151 4567890',
    loanAmount: 390000,
    purchasePrice: 470000,
    city: 'Frankfurt',
    visaType: 'EU Citizen',
    employmentType: 'Employed',
    monthlyNetIncome: 4900,
    stage: 'Document Collection',
    advisorEmail: 'mortgageadvisor@gmail.com',
    sourceName: 'Typeform Expat Mortgage Funnel',
    notes: 'Uploaded 3 salary slips, SCHUFA report 98.7%, waiting on Grundbuch extract.',
  },
  {
    firstName: 'Emily',
    lastName: 'Ross',
    email: 'emily.ross@berlin-design.io',
    phone: '+49 160 3456789',
    loanAmount: 520000,
    purchasePrice: 640000,
    city: 'Berlin',
    visaType: 'EU Blue Card',
    employmentType: 'Employed',
    monthlyNetIncome: 5900,
    stage: 'Bank Submission',
    advisorEmail: 'mortgageadvisor@gmail.com',
    sourceName: 'Immobilienscout24 Expat Leads',
    notes: 'Application dispatched to ING-DiBa and Commerzbank with 3.45% indicative rate.',
  },
  {
    firstName: 'Lucas',
    lastName: 'Moreau',
    email: 'lucas.moreau@aero-cologne.de',
    phone: '+49 172 6543210',
    loanAmount: 420000,
    purchasePrice: 530000,
    city: 'Cologne',
    visaType: 'EU Citizen',
    employmentType: 'Employed',
    monthlyNetIncome: 5100,
    stage: 'Won',
    advisorEmail: 'brokerageadmin@gmail.com',
    sourceName: 'Manual Entry',
    notes: 'Official Darlehenszusage issued by DSL Bank. Loan agreement signed.',
  },
  {
    firstName: 'Anna',
    lastName: 'Weber',
    email: 'anna.weber@hamburg-creatives.de',
    phone: '+49 174 8765432',
    loanAmount: 360000,
    purchasePrice: 440000,
    city: 'Hamburg',
    visaType: 'Freelance / Self-Employed (Freiberufler)',
    employmentType: 'Self-Employed',
    monthlyNetIncome: 4500,
    stage: 'Lost',
    advisorEmail: 'mortgageadvisor@gmail.com',
    sourceName: 'Immobilienscout24 Expat Leads',
    notes: 'Notary appointment scheduled at Notariat Alster for deed signing and Grundschuld filing.',
  },
  {
    firstName: 'Vikram',
    lastName: 'Singh',
    email: 'vikram.singh@auto-stuttgart.de',
    phone: '+49 152 1122334',
    loanAmount: 590000,
    purchasePrice: 740000,
    city: 'Stuttgart',
    visaType: 'EU Blue Card',
    employmentType: 'Employed',
    monthlyNetIncome: 6200,
    stage: 'New',
    advisorEmail: null,
    sourceName: 'Immobilienscout24 Expat Leads',
    notes: 'Unassigned expat lead. Senior powertrain engineer at Mercedes-Benz Group.',
  },
];
