import mongoose from 'mongoose';

const TaskSchema = new mongoose.Schema(
  {
    brokerageId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Brokerage',
      required: true,
      index: true,
    },
    title: { type: String, required: true },
    description: { type: String, default: '' },
    leadId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Lead',
      default: null,
      index: true,
    },
    assignedAdvisorId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
      index: true,
    },
    priority: {
      type: String,
      enum: ['high', 'medium', 'low'],
      default: 'medium',
    },
    dueAt: { type: Date, required: true, index: true },
    isCompleted: { type: Boolean, default: false, index: true },
    completedAt: { type: Date, default: null, index: true },
    // Intelligent Stage Task Lifecycle Fields
    stage: {
      type: String,
      default: null,
      index: true,
    },
    isAutoGenerated: {
      type: Boolean,
      default: false,
      index: true,
    },
    status: {
      type: String,
      enum: ['pending', 'completed', 'superseded', 'cancelled'],
      default: 'pending',
      index: true,
    },
    completedReason: {
      type: String,
      default: null,
    },
  },
  { timestamps: true }
);

// Compound indexes for optimal performance across tenant filtering and archive/active views
TaskSchema.index({ brokerageId: 1, isCompleted: 1, completedAt: -1 });
TaskSchema.index({ brokerageId: 1, assignedAdvisorId: 1, isCompleted: 1 });
TaskSchema.index({ brokerageId: 1, dueAt: 1 });

export default mongoose.model('Task', TaskSchema);

